from __future__ import annotations

from fractions import Fraction
from pathlib import Path
from typing import Any


def _fraction(value: str) -> Fraction:
    if "/" in value:
        numerator, denominator = value.split("/", 1)
        return Fraction(int(numerator), int(denominator))
    return Fraction(value)


def seconds_to_frame(seconds: float | None, fps: Fraction) -> int | None:
    if seconds is None:
        return None
    return max(0, round(float(seconds * fps)))


def emit_vpy(
    source: str,
    zones_payload: dict[str, Any],
    output_path: Path,
    fps: str = "24000/1001",
) -> None:
    fps_fraction = _fraction(fps)
    zones = []
    for zone in zones_payload.get("zones", []):
        start = seconds_to_frame(zone.get("start_seconds"), fps_fraction)
        end_seconds = zone.get("end_seconds")
        end = seconds_to_frame(end_seconds, fps_fraction)
        if end is not None:
            end = max(0, end - 1)
        zones.append(
            {
                "start": start,
                "end": end,
                "label": zone.get("label"),
                "action": zone.get("action"),
                "height": zone.get("candidate_height"),
                "kernel": zone.get("kernel"),
                "confidence": zone.get("confidence"),
            }
        )

    lines = [
        "import vapoursynth as vs",
        "",
        "core = vs.core",
        f"src = core.lsmas.LWLibavSource({source!r})",
        "",
        "# Generated by anime-descale-assist.",
        "# Review zones and QC previews before encoding from this script.",
        "",
        "def native_width(clip, height):",
        "    return max(16, round(clip.width * height / clip.height))",
        "",
        "def descale_candidate(clip, height, kernel):",
        "    width = native_width(clip, height)",
        "    if kernel == 'bilinear':",
        "        native = core.descale.Debilinear(clip, width, height)",
        "    elif kernel == 'catrom':",
        "        native = core.descale.Debicubic(clip, width, height, b=0, c=0.5)",
        "    elif kernel == 'bicubicsharp':",
        "        native = core.descale.Debicubic(clip, width, height, b=0, c=0.75)",
        "    elif kernel == 'lanczos3':",
        "        native = core.descale.Delanczos(clip, width, height, taps=3)",
        "    else:",
        "        raise ValueError(f'unsupported kernel: {kernel}')",
        "    return core.resize.Spline36(native, width=clip.width, height=clip.height)",
        "",
        "ZONES = [",
    ]
    for zone in zones:
        lines.append(f"    {zone!r},")
    lines.extend(
        [
            "]",
            "",
            "candidate_clips = {}",
            "for zone in ZONES:",
            "    if zone['action'] not in {'descale', 'review'}:",
            "        continue",
            "    if zone['height'] is None or zone['kernel'] is None:",
            "        continue",
            "    key = (zone['height'], zone['kernel'])",
            "    if key not in candidate_clips:",
            "        candidate_clips[key] = descale_candidate(src, zone['height'], zone['kernel'])",
            "",
            "def pick_frame(n):",
            "    for zone in ZONES:",
            "        start = zone['start']",
            "        end = zone['end']",
            "        if start is None or end is None:",
            "            continue",
            "        if start <= n <= end and zone['action'] == 'descale':",
            "            return candidate_clips[(zone['height'], zone['kernel'])]",
            "    return src",
            "",
            "out = core.std.FrameEval(src, pick_frame)",
            "out.set_output()",
            "",
        ]
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
